services:
  backend:
    image: node:18-bullseye
    working_dir: /app/backend
    command: sh -c "npm install && npm run seed && npm run dev"
    volumes:
      - ./:/app
    ports:
      - "3001:3001"

  frontend:
    image: node:18-bullseye
    working_dir: /app/frontend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
